@api_HostAddress = http://localhost:5131
@countryId = 2
@hotelId = 200

###
# Countries - Get all
GET {{api_HostAddress}}/api/countries
Accept: application/json

###
# Countries - Get by id
GET {{api_HostAddress}}/api/countries/{{countryId}}
Accept: application/json

###
# Countries - Create
POST {{api_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Bangladesh",
  "shortName": "BD"
}

###
# Countries - Update
PUT {{api_HostAddress}}/api/countries/{{countryId}}
Content-Type: application/json

{
  "id": {{countryId}},
  "name": "Mali",
  "shortName": "SA"
}

###
# Countries - Delete
DELETE {{api_HostAddress}}/api/countries/{{countryId}}

###
# Hotels - Get all
GET {{api_HostAddress}}/api/hotels
Accept: application/json

###
# Hotels - Get by id
GET {{api_HostAddress}}/api/hotels/{{hotelId}}
Accept: application/json

###
# Hotels - Create
POST {{api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "name": "Testy Treat Hotel",
  "address": "Banani",
  "rating": 4,
  "countryId": {{countryId}}
}

###
# Hotels - Update
PUT {{api_HostAddress}}/api/hotels/{{hotelId}}
Content-Type: application/json

{
  "id": {{hotelId}},
  "name": "Hazi biriyani resturent 2nd branch ",
  "address": "New Market",
  "rating": 4,
  "countryId": {{countryId}}
}

###
# Hotels - Delete
DELETE {{api_HostAddress}}/api/hotels/{{hotelId}}

###
# Auth - Register User
POST {{api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Password123!",
  "firstName": "Shafiul",
  "lastName": "Islam"
}






###
# Auth - Login User
POST {{api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Password123!"
}

###
# Default Identity Auth - Register
POST {{api_HostAddress}}/api/default-auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Password123!"
}

###
# Default Identity Auth - Login
POST {{api_HostAddress}}/api/default-auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Password123!"
}
