@api_HostAddress = http://localhost:5131
@countryId = 1002
@hotelId = 1002

###
# Countries - Get all
GET {{api_HostAddress}}/api/countries
Accept: application/json

###
# Countries - Get by id
GET {{api_HostAddress}}/api/countries/{{countryId}}
Accept: application/json

###
# Countries - Create Bangladesh
POST {{api_HostAddress}}/api/countries
Content-Type: application/json

{
    "id": 13,
  "name": "Turkey",
  "shortName": "TR"
}

###
# Countries - Update
PUT {{api_HostAddress}}/api/countries/{{countryId}}
Content-Type: application/json

{
  "id": {{countryId}},
  "name": "Bhutan",
  "shortName": "BT"
}

###
# Countries - Delete
DELETE {{api_HostAddress}}/api/countries/{{countryId}}

###
# Hotels - Get all
GET {{api_HostAddress}}/api/hotels
Accept: application/json

###
# Hotels - Get by id
GET {{api_HostAddress}}/api/hotels/{{hotelId}}
Accept: application/json

###
# Hotels - Create
POST {{api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "name": "Ruposhi Bangla Hotel",
  "address": "Motijheel",
  "rating": 5,
  "countryId": {{countryId}}
}

###
# Hotels - Update
PUT {{api_HostAddress}}/api/hotels/{{hotelId}}
Content-Type: application/json

{
  "id": {{hotelId}},
  "name": "Radisson Blu Dhaka",
  "address": "Banani",
  "rating": 5,
  "countryId": {{countryId}}
}

###
# Hotels - Delete
DELETE {{api_HostAddress}}/api/hotels/{{hotelId}}
